project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Workshop

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-tools: true

execute:
  warning: false
  message: false
